repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
        - id: trailing-whitespace
        - id: check-json
        - id: end-of-file-fixer
        - id: detect-private-key
        - id: debug-statements
        - id: check-added-large-files

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
        - id: python-no-log-warn
        - id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
        - id: clang-format

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        args: [--line-length=120]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

-   repo: local
    hooks:
      - id: verify-function-names
        name: Verify Function Names
        entry: python C:\\Temp\\applications.automation.advanced-system-tools-analytics\\verify_function_name.py
        language: python
        files: \.py$

      - id: verify-class-names
        name: Verify Class Names
        entry: python C:\\Temp\\applications.automation.advanced-system-tools-analytics\\verify_class_name.py
        language: python
        files: \.py$
